name: fastib2pci
on:
  push:
    branches:
      - main  
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:  
      - run: |
          echo "${{ github.repository }}" &&
          echo "${{ GITHUB_REPOSITORY }}
